export const NEW_NOTIFICATION = 'NEW_NOTIFICATION';
export const READ_NEW_NOTIFICATION = 'READ_NEW_NOTIFICATION';
export const FRIEND_REQUEST = 'FRIEND_REQUEST';

export const NOTIFICATION_LOADING = 'NOTIFICATION_LOADING';
export const NOTIFICATION_SUCCESS = 'NOTIFICATION_SUCCESS';
export const LOAD_NOTIFICATION = 'LOAD_NOTIFICATION';
export const SET_GROUP_CHAT_MODAL_STATUS = 'SET_GROUP_CHAT_MODAL_STATUS';
